# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/nutrilens_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=3000

app.jwt.secret=calai_super_secret_jwt_key_change_in_production_min_32_chars
app.jwt.expiration=2592000000

app.gemini.api-key=AIzaSyCMPbIFcKw7ks3owzSwpF7cZDZ2RTPwQVc

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jackson.property-naming-strategy=SNAKE_CASE
